name: Test, Coverage, Build and Release apks
on: push
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: clean cache
        run: flutter clean
        
      - name: GET Flutter
        run: flutter pub get
      
      - name : upgrade flutter
        run: flutter upgrade
        
      - name : flutter pub 
        run: flutter pub upgrade
        
      - name: flutter test coverage
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
      
      - name: Build debug apk
        run: ./gradlew clean assembleDebug

      - name: Create release and upload apk
        uses: underwindfall/create-release-with-debugapk@v2.0.0
        env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: v1.0.0
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: gotogether.apk
          asset_content_type: application/zip

